# Generated by Django 5.0.6 on 2024-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('birthday', models.TextField()),
                ('age', models.TextField()),
                ('address', models.TextField()),
                ('address_link', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('email_link', models.TextField()),
                ('telegram', models.TextField()),
                ('tg_link', models.TextField()),
                ('vd_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComeJoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('address_link', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('email_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('yellow_description', models.TextField()),
                ('yd_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('datatime', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsTop5Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('name', models.CharField(max_length=155, verbose_name='Student name')),
                ('overall', models.CharField(max_length=155, verbose_name='Overall')),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('admin', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
