# Generated by Django 5.0.6 on 2024-06-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_studentstop5results_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.TextField(),
        ),
    ]
