# Generated by Django 5.0.6 on 2024-06-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutme_address_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsresults',
            name='datatime',
            field=models.TextField(verbose_name='Sana va vaqt'),
        ),
    ]
