# Generated by Django 5.0.6 on 2024-06-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_studentsresults_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comejoinus',
            name='address_link',
            field=models.TextField(verbose_name='Manzil havolasi'),
        ),
        migrations.AlterField(
            model_name='comejoinus',
            name='email_link',
            field=models.TextField(verbose_name='Elektron pochta havolasi'),
        ),
    ]
