# Generated by Django 5.0.6 on 2024-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_comejoinus_address_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comejoinus',
            name='address_link',
            field=models.TextField(max_length=555, verbose_name='Manzil havolasi'),
        ),
        migrations.AlterField(
            model_name='comejoinus',
            name='email_link',
            field=models.TextField(max_length=555, verbose_name='Elektron pochta havolasi'),
        ),
    ]
