# Generated by Django 5.0.6 on 2024-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_comejoinus_address_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('wheredidyoulearn', models.TextField(verbose_name='Where')),
                ('course', models.TextField(verbose_name='Kurs')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('wheredidyouwork', models.TextField(verbose_name='Where')),
                ('role', models.TextField(verbose_name='Role')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(verbose_name='End')),
            ],
        ),
        migrations.AlterField(
            model_name='comejoinus',
            name='email',
            field=models.TextField(verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='comejoinus',
            name='email_link',
            field=models.TextField(max_length=555, verbose_name='Telegram havolasi'),
        ),
    ]
