# Generated by Django 5.0.6 on 2024-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_education_title_remove_experience_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.TextField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.TextField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.TextField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.TextField(verbose_name='Start'),
        ),
    ]
