# Generated by Django 5.0.6 on 2024-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Nashr qilish'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Nashr qilish'),
        ),
    ]
