# Generated by Django 5.0.6 on 2024-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_education_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(verbose_name='Kurs')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilish')),
                ('price', models.TextField(verbose_name='Price')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
